#!/bin/bash
# NEXTFLOW TASK: DADA2_LEARN_ERRORS (16S-Plate1Pool-Rep1)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_tree() {
    local pid=$1

    declare -a ALL_CHILDREN
    while read P PP;do
        ALL_CHILDREN[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    pstat() {
        local x_pid=$1
        local STATUS=$(2> /dev/null < /proc/$1/status grep -E 'Vm|ctxt')

        if [ $? = 0 ]; then
        local  x_vsz=$(echo "$STATUS" | grep VmSize | awk '{print $2}' || echo -n '0')
        local  x_rss=$(echo "$STATUS" | grep VmRSS | awk '{print $2}' || echo -n '0')
        local x_peak=$(echo "$STATUS" | grep -E 'VmPeak|VmHWM' | sed 's/^.*:\s*//' | sed 's/[\sa-zA-Z]*$//' | tr '\n' ' ' || echo -n '0 0')
        local x_pmem=$(awk -v rss=$x_rss -v mem_tot=$mem_tot 'BEGIN {printf "%.0f", rss/mem_tot*100*10}' || echo -n '0')
        local vol_ctxt=$(echo "$STATUS" | grep '\bvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        local inv_ctxt=$(echo "$STATUS" | grep '\bnonvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        cpu_stat[x_pid]="$x_pid $x_pmem $x_vsz $x_rss $x_peak $vol_ctxt $inv_ctxt"
        fi
    }

    pwalk() {
        pstat $1
        for i in ${ALL_CHILDREN[$1]:=}; do pwalk $i; done
    }

    pwalk $1
}

nxf_stat() {
    cpu_stat=()
    nxf_tree $1

    declare -a sum=(0 0 0 0 0 0 0 0)
    local pid
    local i
    for pid in "${!cpu_stat[@]}"; do
        local row=(${cpu_stat[pid]})
        [ $NXF_DEBUG = 1 ] && echo "++ stat mem=${row[*]}"
        for i in "${!row[@]}"; do
        if [ $i != 0 ]; then
            sum[i]=$((sum[i]+row[i]))
        fi
        done
    done

    [ $NXF_DEBUG = 1 ] && echo -e "++ stat SUM=${sum[*]}"

    for i in {1..7}; do
        if [ ${sum[i]} -lt ${cpu_peak[i]} ]; then
            sum[i]=${cpu_peak[i]}
        else
            cpu_peak[i]=${sum[i]}
        fi
    done

    [ $NXF_DEBUG = 1 ] && echo -e "++ stat PEAK=${sum[*]}\n"
    nxf_stat_ret=(${sum[*]})
}

nxf_mem_watch() {
    set -o pipefail
    local pid=$1
    local trace_file=.command.trace
    local count=0;
    declare -a cpu_stat=(0 0 0 0 0 0 0 0)
    declare -a cpu_peak=(0 0 0 0 0 0 0 0)
    local mem_tot=$(< /proc/meminfo grep MemTotal | awk '{print $2}')
    local timeout
    local DONE
    local STOP=''

    [ $NXF_DEBUG = 1 ] && nxf_sleep 0.2 && ps fx

    while true; do
        nxf_stat $pid
        if [ $count -lt 10 ]; then timeout=1;
        elif [ $count -lt 120 ]; then timeout=5;
        else timeout=30;
        fi
        read -t $timeout -r DONE || true
        [[ $DONE ]] && break
        if [ ! -e /proc/$pid ]; then
            [ ! $STOP ] && STOP=$(nxf_date)
            [ $(($(nxf_date)-STOP)) -gt 10000 ] && break
        fi
        count=$((count+1))
    done

    echo "%mem=${nxf_stat_ret[1]}"      >> $trace_file
    echo "vmem=${nxf_stat_ret[2]}"      >> $trace_file
    echo "rss=${nxf_stat_ret[3]}"       >> $trace_file
    echo "peak_vmem=${nxf_stat_ret[4]}" >> $trace_file
    echo "peak_rss=${nxf_stat_ret[5]}"  >> $trace_file
    echo "vol_ctxt=${nxf_stat_ret[6]}"  >> $trace_file
    echo "inv_ctxt=${nxf_stat_ret[7]}"  >> $trace_file
}

nxf_write_trace() {
    echo "nextflow.trace/v2"           > $trace_file
    echo "realtime=$wall_time"         >> $trace_file
    echo "%cpu=$ucpu"                  >> $trace_file
    echo "rchar=${io_stat1[0]}"        >> $trace_file
    echo "wchar=${io_stat1[1]}"        >> $trace_file
    echo "syscr=${io_stat1[2]}"        >> $trace_file
    echo "syscw=${io_stat1[3]}"        >> $trace_file
    echo "read_bytes=${io_stat1[4]}"   >> $trace_file
    echo "write_bytes=${io_stat1[5]}"  >> $trace_file
}

nxf_trace_mac() {
    local start_millis=$(nxf_date)

    /bin/bash -ue /data/microscape_v2/nextflow/work/35/b75c1a77e12e90adcdd5a4ec6b2c89/.command.sh

    local end_millis=$(nxf_date)
    local wall_time=$((end_millis-start_millis))
    local ucpu=''
    local io_stat1=('' '' '' '' '' '')
    nxf_write_trace
}

nxf_fd() {
    local FD=11
    while [ -e /proc/$$/fd/$FD ]; do FD=$((FD+1)); done
    echo $FD
}

nxf_trace_linux() {
    local pid=$$
    command -v ps &>/dev/null || { >&2 echo "Command 'ps' required by nextflow to collect task metrics cannot be found"; exit 1; }
    local num_cpus=$(< /proc/cpuinfo grep '^processor' -c)
    local tot_time0=$(grep '^cpu ' /proc/stat | awk '{sum=$2+$3+$4+$5+$6+$7+$8+$9; printf "%.0f",sum}')
    local cpu_time0=$(2> /dev/null < /proc/$pid/stat awk '{printf "%.0f", ($16+$17)*10 }' || echo -n 'X')
    local io_stat0=($(2> /dev/null < /proc/$pid/io sed 's/^.*:\s*//' | head -n 6 | tr '\n' ' ' || echo -n '0 0 0 0 0 0'))
    local start_millis=$(nxf_date)
    trap 'kill $mem_proc' ERR
    
    /bin/bash -ue /data/microscape_v2/nextflow/work/35/b75c1a77e12e90adcdd5a4ec6b2c89/.command.sh &
    local task=$!

    mem_fd=$(nxf_fd)
    eval "exec $mem_fd> >(nxf_mem_watch $task)"
    local mem_proc=$!

    wait $task

    local end_millis=$(nxf_date)
    local tot_time1=$(grep '^cpu ' /proc/stat | awk '{sum=$2+$3+$4+$5+$6+$7+$8+$9; printf "%.0f",sum}')
    local cpu_time1=$(2> /dev/null < /proc/$pid/stat awk '{printf "%.0f", ($16+$17)*10 }' || echo -n 'X')
    local ucpu=$(awk -v p1=$cpu_time1 -v p0=$cpu_time0 -v t1=$tot_time1 -v t0=$tot_time0 -v n=$num_cpus 'BEGIN { pct=(p1-p0)/(t1-t0)*100*n; printf("%.0f", pct>0 ? pct : 0) }' )

    local io_stat1=($(2> /dev/null < /proc/$pid/io sed 's/^.*:\s*//' | head -n 6 | tr '\n' ' ' || echo -n '0 0 0 0 0 0'))
    local i
    for i in {0..5}; do
        io_stat1[i]=$((io_stat1[i]-io_stat0[i]))
    done

    local wall_time=$((end_millis-start_millis))
    [ $NXF_DEBUG = 1 ] && echo "+++ STATS %CPU=$ucpu TIME=$wall_time I/O=${io_stat1[*]}"

    echo "nextflow.trace/v2"           > $trace_file
    echo "realtime=$wall_time"         >> $trace_file
    echo "%cpu=$ucpu"                  >> $trace_file
    echo "rchar=${io_stat1[0]}"        >> $trace_file
    echo "wchar=${io_stat1[1]}"        >> $trace_file
    echo "syscr=${io_stat1[2]}"        >> $trace_file
    echo "syscw=${io_stat1[3]}"        >> $trace_file
    echo "read_bytes=${io_stat1[4]}"   >> $trace_file
    echo "write_bytes=${io_stat1[5]}"  >> $trace_file

    [ -e /proc/$mem_proc ] && eval "echo 'DONE' >&$mem_fd" || true
    wait $mem_proc 2>/dev/null || true
    while [ -e /proc/$mem_proc ]; do nxf_sleep 0.1; done
}

nxf_trace() {
    local trace_file=.command.trace
    touch $trace_file
    if [[ $(uname) = Darwin ]]; then
        nxf_trace_mac
    else
        nxf_trace_linux
    fi
}
# aws cli retry config
export AWS_RETRY_MODE=standard 
export AWS_MAX_ATTEMPTS=5
# aws helper
nxf_s3_upload() {
    local name=$1
    local s3path=$2
    if [[ "$name" == - ]]; then
      aws s3 cp --only-show-errors --storage-class STANDARD - "$s3path"
    elif [[ -d "$name" ]]; then
      aws s3 cp --only-show-errors --recursive --storage-class STANDARD "$name" "$s3path/$name"
    else
      aws s3 cp --only-show-errors --storage-class STANDARD "$name" "$s3path/$name"
    fi
}

nxf_s3_download() {
    local source=$1
    local target=$2
    local file_name=$(basename $1)
    local is_dir=$(aws s3 ls $source | grep -F "PRE ${file_name}/" -c)
    if [[ $is_dir == 1 ]]; then
        aws s3 cp --only-show-errors --recursive "$source" "$target"
    else 
        aws s3 cp --only-show-errors "$source" "$target"
    fi
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /data/microscape_v2/nextflow/work/35/b75c1a77e12e90adcdd5a4ec6b2c89/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    sync || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash /data/microscape_v2/nextflow/work/35/b75c1a77e12e90adcdd5a4ec6b2c89/.command.run nxf_trace
}

nxf_stage() {
    true
    # stage input files
    ln -s /data/microscape_v2/nextflow/work/b2/ee61910773e93a8c92047ba1cfb2a7/16S-Plate1Pool-Rep1_F03_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_F03_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/08/2b20a18f6e8ca760f3d3a36bf482f1/16S-Plate1Pool-Rep1_F07_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_F07_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/42/bf054f7ea4373f1bf6483fa48ff2b2/16S-Plate1Pool-Rep1_B05_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_B05_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/0e/667fe9038798dee465a2be326da9f8/16S-Plate1Pool-Rep1_G08_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_G08_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/a4/8a451e87d6d51cb97009e6dff77741/16S-Plate1Pool-Rep1_B01_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_B01_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/b7/0e8501021e3febe093d9f2369e3f8a/16S-Plate1Pool-Rep1_D04_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_D04_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/f6/e408a71f8d27db7bae9d7af0580509/16S-Plate1Pool-Rep1_D08_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_D08_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/93/a9036a54e49fa3cbc83ed1601413b8/16S-Plate1Pool-Rep1_H08_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_H08_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/ef/e68c82ba42da03b9daaaaa496eb5f8/16S-Plate1Pool-Rep1_F01_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_F01_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/21/b642d1c3c6aee74974284ebf57702d/16S-Plate1Pool-Rep1_B02_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_B02_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/c1/4be83bb72af3362a754ba2563f6d06/16S-Plate1Pool-Rep1_H07_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_H07_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/e5/3a6670257a1dedace9b840008c4123/16S-Plate1Pool-Rep1_G07_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_G07_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/a2/04af3cfcc6e716b71789b5ca118a74/16S-Plate1Pool-Rep1_E05_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_E05_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/86/489fffdddaef62b80fe6322da9350b/16S-Plate1Pool-Rep1_G05_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_G05_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/61/0cdcd7d095b2a4d576359e228edc39/16S-Plate1Pool-Rep1_E07_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_E07_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/73/f607d1531ddd0bba872c470e306e7a/16S-Plate1Pool-Rep1_D02_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_D02_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/ca/6f0a2da716bbbfb4ed3147f38406f3/16S-Plate1Pool-Rep1_D09_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_D09_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/05/2a96f58a32bc1b150891062c676b1a/16S-Plate1Pool-Rep1_A07_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_A07_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/a1/973010324c04d6bc8c4e7883c2a379/16S-Plate1Pool-Rep1_H01_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_H01_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/0e/56c0400a11a99358adf134223cc894/16S-Plate1Pool-Rep1_B09_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_B09_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/16/01168753fc9f87bf8f976fa3a4d0cd/16S-Plate1Pool-Rep1_E03_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_E03_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/3b/c7c320b37ee2131f25bd77ad2c89ed/16S-Plate1Pool-Rep1_H09_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_H09_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/3f/fdd04fb459ec8b2065b4d659b0a59e/16S-Plate1Pool-Rep1_F08_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_F08_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/26/fed90351fa1a7cfe1beec6667a2006/16S-Plate1Pool-Rep1_C04_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_C04_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/d8/51d2e81dcc2de519c2d9ffce42be37/16S-Plate1Pool-Rep1_E01_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_E01_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/7b/d2170f5aefb43c6a6ea46cbbc0447a/16S-Plate1Pool-Rep1_D05_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_D05_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/c8/7360631432d669c6edf7cc6d6d4703/16S-Plate1Pool-Rep1_H03_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_H03_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/e2/5829415a5c49d216f2fcfd23c0d6bc/16S-Plate1Pool-Rep1_A05_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_A05_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/1e/8be2fb8d1477470b84f60bff9b5274/16S-Plate1Pool-Rep1_B10_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_B10_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/9f/92042bc9fce51144d6d75bf86d00bb/16S-Plate1Pool-Rep1_C06_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_C06_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/90/f706627d04eabcd9dff755bd5c78ae/16S-Plate1Pool-Rep1_F04_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_F04_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/8c/9353580dc78cfe25ce2cee5aad57e3/16S-Plate1Pool-Rep1_E09_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_E09_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/da/6bfa7708b716a0ff7b977e1099856a/16S-Plate1Pool-Rep1_D06_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_D06_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/c0/e46a81c274b3963e6f86ba7b20cf2d/16S-Plate1Pool-Rep1_H06_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_H06_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/1f/e2504accbf0c21d29bfeba27dd7b0c/16S-Plate1Pool-Rep1_C01_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_C01_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/60/cf75a57b9605a6793f01d662445813/16S-Plate1Pool-Rep1_E08_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_E08_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/17/e7b347cae10c7571d2eca0426e245b/16S-Plate1Pool-Rep1_F06_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_F06_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/f7/941c333d558a4abe2a45927b243ac8/16S-Plate1Pool-Rep1_B07_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_B07_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/46/eb735f4d8f1021399712282b91352a/16S-Plate1Pool-Rep1_H05_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_H05_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/5e/5cfe7f72ae2ad2d240a0dd44d572fe/16S-Plate1Pool-Rep1_D03_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_D03_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/f3/3eb119f9146ed97e9f7acf7aa0f204/16S-Plate1Pool-Rep1_C09_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_C09_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/0e/be4e46e15fb77a04aed2b2b8f2ac4f/16S-Plate1Pool-Rep1_G09_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_G09_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/9b/1c8c78aaba2027ff6441bc3de54286/16S-Plate1Pool-Rep1_G03_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_G03_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/18/bc8a42206e998b93d2461005d53f24/16S-Plate1Pool-Rep1_C07_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_C07_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/b0/15337274674afff9087ce00789fb0f/16S-Plate1Pool-Rep1_B06_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_B06_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/d6/f90dc483be68bfc1f8e22c4024f74f/16S-Plate1Pool-Rep1_C08_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_C08_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/4e/7e7f64a0f1efb0bcfeb02e03d21224/16S-Plate1Pool-Rep1_H04_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_H04_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/97/f84efa5caa9ed6e81614d4c9aaf1f2/16S-Plate1Pool-Rep1_E02_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_E02_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/4c/7d581bfb37b9a817010096eeb0f992/16S-Plate1Pool-Rep1_A04_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_A04_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/7c/94e636c1f6a989cb467df15ea12bb3/16S-Plate1Pool-Rep1_E06_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_E06_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/a2/88bc67385a8318ff70305e395ee992/16S-Plate1Pool-Rep1_A06_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_A06_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/5c/097e26e3eaffc06a791075ec1e020e/16S-Plate1Pool-Rep1_D07_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_D07_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/9c/501916170162998d78d4da87682dcc/16S-Plate1Pool-Rep1_B04_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_B04_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/9d/641d8ea645078ffab18fd5465aad51/16S-Plate1Pool-Rep1_C03_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_C03_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/3a/4cff8765f5f967c1481f4b581aad82/16S-Plate1Pool-Rep1_A03_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_A03_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/b2/98ec4c8afa61820070f6fdcdd17a33/16S-Plate1Pool-Rep1_F05_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_F05_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/e8/ff9509bc991e1d075365d5cc814887/16S-Plate1Pool-Rep1_B03_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_B03_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/67/2d7307aa1d72ff910af5967c5d1fb2/16S-Plate1Pool-Rep1_A02_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_A02_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/5a/bbc4bc3f4efc1dfa1f45bbf3fe022a/16S-Plate1Pool-Rep1_E10_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_E10_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/e3/f904e5844cf4e8ee902732370299e0/16S-Plate1Pool-Rep1_G06_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_G06_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/aa/799a573afb9bb0cb487f4788d39882/16S-Plate1Pool-Rep1_A09_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_A09_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/cb/39cfe133e755e916b3725b91e16e98/16S-Plate1Pool-Rep1_G01_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_G01_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/23/6799bd00da099cf286e96fbc6a37e4/16S-Plate1Pool-Rep1_F09_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_F09_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/5a/98a0c0ee1bc21f289c5eedd3b73239/16S-Plate1Pool-Rep1_B08_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_B08_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/02/5a4b552229d53536bd016a9533232d/16S-Plate1Pool-Rep1_D01_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_D01_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/c9/dfd53a95688fbfc2235b2986749f63/16S-Plate1Pool-Rep1_H02_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_H02_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/d9/1819b10d8d1ab7ff4311cff5132983/16S-Plate1Pool-Rep1_A08_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_A08_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/93/6d9864a02a608277a8bcd41010fd24/16S-Plate1Pool-Rep1_G02_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_G02_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/95/769d224c53c3d1def3c59906829704/16S-Plate1Pool-Rep1_C02_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_C02_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/0a/bb9bfb1c7f7fbffbfdf7a0f77045d4/16S-Plate1Pool-Rep1_H10_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_H10_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/d3/33ff717c72ded445337122b9338cc6/16S-Plate1Pool-Rep1_E04_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_E04_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/e4/d8117cf1055da522709e2983e0880e/16S-Plate1Pool-Rep1_F02_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_F02_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/3d/cd4e6c3a345fe8a017e0b8cb8eeb7c/16S-Plate1Pool-Rep1_G04_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_G04_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/4e/dfeeea4620bb0f74978b446c0c5a46/16S-Plate1Pool-Rep1_C05_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_C05_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/37/871ddc8c1fa4bd3f8a35bb681e4641/16S-Plate1Pool-Rep1_A01_R1.filt.fastq.gz 16S-Plate1Pool-Rep1_A01_R1.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/b2/ee61910773e93a8c92047ba1cfb2a7/16S-Plate1Pool-Rep1_F03_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_F03_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/08/2b20a18f6e8ca760f3d3a36bf482f1/16S-Plate1Pool-Rep1_F07_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_F07_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/42/bf054f7ea4373f1bf6483fa48ff2b2/16S-Plate1Pool-Rep1_B05_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_B05_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/0e/667fe9038798dee465a2be326da9f8/16S-Plate1Pool-Rep1_G08_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_G08_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/a4/8a451e87d6d51cb97009e6dff77741/16S-Plate1Pool-Rep1_B01_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_B01_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/b7/0e8501021e3febe093d9f2369e3f8a/16S-Plate1Pool-Rep1_D04_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_D04_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/f6/e408a71f8d27db7bae9d7af0580509/16S-Plate1Pool-Rep1_D08_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_D08_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/93/a9036a54e49fa3cbc83ed1601413b8/16S-Plate1Pool-Rep1_H08_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_H08_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/ef/e68c82ba42da03b9daaaaa496eb5f8/16S-Plate1Pool-Rep1_F01_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_F01_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/21/b642d1c3c6aee74974284ebf57702d/16S-Plate1Pool-Rep1_B02_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_B02_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/c1/4be83bb72af3362a754ba2563f6d06/16S-Plate1Pool-Rep1_H07_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_H07_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/e5/3a6670257a1dedace9b840008c4123/16S-Plate1Pool-Rep1_G07_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_G07_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/a2/04af3cfcc6e716b71789b5ca118a74/16S-Plate1Pool-Rep1_E05_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_E05_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/86/489fffdddaef62b80fe6322da9350b/16S-Plate1Pool-Rep1_G05_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_G05_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/61/0cdcd7d095b2a4d576359e228edc39/16S-Plate1Pool-Rep1_E07_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_E07_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/73/f607d1531ddd0bba872c470e306e7a/16S-Plate1Pool-Rep1_D02_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_D02_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/ca/6f0a2da716bbbfb4ed3147f38406f3/16S-Plate1Pool-Rep1_D09_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_D09_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/05/2a96f58a32bc1b150891062c676b1a/16S-Plate1Pool-Rep1_A07_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_A07_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/a1/973010324c04d6bc8c4e7883c2a379/16S-Plate1Pool-Rep1_H01_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_H01_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/0e/56c0400a11a99358adf134223cc894/16S-Plate1Pool-Rep1_B09_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_B09_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/16/01168753fc9f87bf8f976fa3a4d0cd/16S-Plate1Pool-Rep1_E03_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_E03_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/3b/c7c320b37ee2131f25bd77ad2c89ed/16S-Plate1Pool-Rep1_H09_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_H09_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/3f/fdd04fb459ec8b2065b4d659b0a59e/16S-Plate1Pool-Rep1_F08_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_F08_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/26/fed90351fa1a7cfe1beec6667a2006/16S-Plate1Pool-Rep1_C04_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_C04_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/d8/51d2e81dcc2de519c2d9ffce42be37/16S-Plate1Pool-Rep1_E01_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_E01_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/7b/d2170f5aefb43c6a6ea46cbbc0447a/16S-Plate1Pool-Rep1_D05_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_D05_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/c8/7360631432d669c6edf7cc6d6d4703/16S-Plate1Pool-Rep1_H03_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_H03_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/e2/5829415a5c49d216f2fcfd23c0d6bc/16S-Plate1Pool-Rep1_A05_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_A05_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/1e/8be2fb8d1477470b84f60bff9b5274/16S-Plate1Pool-Rep1_B10_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_B10_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/9f/92042bc9fce51144d6d75bf86d00bb/16S-Plate1Pool-Rep1_C06_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_C06_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/90/f706627d04eabcd9dff755bd5c78ae/16S-Plate1Pool-Rep1_F04_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_F04_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/8c/9353580dc78cfe25ce2cee5aad57e3/16S-Plate1Pool-Rep1_E09_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_E09_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/da/6bfa7708b716a0ff7b977e1099856a/16S-Plate1Pool-Rep1_D06_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_D06_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/c0/e46a81c274b3963e6f86ba7b20cf2d/16S-Plate1Pool-Rep1_H06_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_H06_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/1f/e2504accbf0c21d29bfeba27dd7b0c/16S-Plate1Pool-Rep1_C01_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_C01_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/60/cf75a57b9605a6793f01d662445813/16S-Plate1Pool-Rep1_E08_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_E08_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/17/e7b347cae10c7571d2eca0426e245b/16S-Plate1Pool-Rep1_F06_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_F06_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/f7/941c333d558a4abe2a45927b243ac8/16S-Plate1Pool-Rep1_B07_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_B07_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/46/eb735f4d8f1021399712282b91352a/16S-Plate1Pool-Rep1_H05_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_H05_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/5e/5cfe7f72ae2ad2d240a0dd44d572fe/16S-Plate1Pool-Rep1_D03_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_D03_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/f3/3eb119f9146ed97e9f7acf7aa0f204/16S-Plate1Pool-Rep1_C09_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_C09_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/0e/be4e46e15fb77a04aed2b2b8f2ac4f/16S-Plate1Pool-Rep1_G09_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_G09_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/9b/1c8c78aaba2027ff6441bc3de54286/16S-Plate1Pool-Rep1_G03_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_G03_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/18/bc8a42206e998b93d2461005d53f24/16S-Plate1Pool-Rep1_C07_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_C07_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/b0/15337274674afff9087ce00789fb0f/16S-Plate1Pool-Rep1_B06_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_B06_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/d6/f90dc483be68bfc1f8e22c4024f74f/16S-Plate1Pool-Rep1_C08_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_C08_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/4e/7e7f64a0f1efb0bcfeb02e03d21224/16S-Plate1Pool-Rep1_H04_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_H04_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/97/f84efa5caa9ed6e81614d4c9aaf1f2/16S-Plate1Pool-Rep1_E02_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_E02_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/4c/7d581bfb37b9a817010096eeb0f992/16S-Plate1Pool-Rep1_A04_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_A04_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/7c/94e636c1f6a989cb467df15ea12bb3/16S-Plate1Pool-Rep1_E06_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_E06_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/a2/88bc67385a8318ff70305e395ee992/16S-Plate1Pool-Rep1_A06_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_A06_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/5c/097e26e3eaffc06a791075ec1e020e/16S-Plate1Pool-Rep1_D07_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_D07_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/9c/501916170162998d78d4da87682dcc/16S-Plate1Pool-Rep1_B04_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_B04_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/9d/641d8ea645078ffab18fd5465aad51/16S-Plate1Pool-Rep1_C03_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_C03_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/3a/4cff8765f5f967c1481f4b581aad82/16S-Plate1Pool-Rep1_A03_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_A03_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/b2/98ec4c8afa61820070f6fdcdd17a33/16S-Plate1Pool-Rep1_F05_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_F05_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/e8/ff9509bc991e1d075365d5cc814887/16S-Plate1Pool-Rep1_B03_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_B03_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/67/2d7307aa1d72ff910af5967c5d1fb2/16S-Plate1Pool-Rep1_A02_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_A02_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/5a/bbc4bc3f4efc1dfa1f45bbf3fe022a/16S-Plate1Pool-Rep1_E10_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_E10_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/e3/f904e5844cf4e8ee902732370299e0/16S-Plate1Pool-Rep1_G06_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_G06_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/aa/799a573afb9bb0cb487f4788d39882/16S-Plate1Pool-Rep1_A09_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_A09_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/cb/39cfe133e755e916b3725b91e16e98/16S-Plate1Pool-Rep1_G01_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_G01_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/23/6799bd00da099cf286e96fbc6a37e4/16S-Plate1Pool-Rep1_F09_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_F09_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/5a/98a0c0ee1bc21f289c5eedd3b73239/16S-Plate1Pool-Rep1_B08_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_B08_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/02/5a4b552229d53536bd016a9533232d/16S-Plate1Pool-Rep1_D01_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_D01_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/c9/dfd53a95688fbfc2235b2986749f63/16S-Plate1Pool-Rep1_H02_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_H02_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/d9/1819b10d8d1ab7ff4311cff5132983/16S-Plate1Pool-Rep1_A08_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_A08_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/93/6d9864a02a608277a8bcd41010fd24/16S-Plate1Pool-Rep1_G02_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_G02_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/95/769d224c53c3d1def3c59906829704/16S-Plate1Pool-Rep1_C02_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_C02_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/0a/bb9bfb1c7f7fbffbfdf7a0f77045d4/16S-Plate1Pool-Rep1_H10_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_H10_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/d3/33ff717c72ded445337122b9338cc6/16S-Plate1Pool-Rep1_E04_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_E04_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/e4/d8117cf1055da522709e2983e0880e/16S-Plate1Pool-Rep1_F02_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_F02_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/3d/cd4e6c3a345fe8a017e0b8cb8eeb7c/16S-Plate1Pool-Rep1_G04_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_G04_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/4e/dfeeea4620bb0f74978b446c0c5a46/16S-Plate1Pool-Rep1_C05_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_C05_R2.filt.fastq.gz
    ln -s /data/microscape_v2/nextflow/work/37/871ddc8c1fa4bd3f8a35bb681e4641/16S-Plate1Pool-Rep1_A01_R2.filt.fastq.gz 16S-Plate1Pool-Rep1_A01_R2.filt.fastq.gz
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /data/microscape_v2/nextflow/work/35/b75c1a77e12e90adcdd5a4ec6b2c89/.command.begin
    set +u
    # beforeScript directive
    export PATH=/data/microscape_v2/nextflow/bin/py:$PATH && mkdir -p '/data/microscape_v2/test_results_py/pipeline_info' && echo 'DADA2_LEARN_ERRORS	START	'$(date -Iseconds) >> '/data/microscape_v2/test_results_py/pipeline_info/pipeline_timing.tsv'
    set -u
    export PATH="$PATH:/data/microscape_v2/nextflow/bin"
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    nxf_stage

    set +e
    ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
    # 'afterScript' directive
    echo 'DADA2_LEARN_ERRORS	END	'$(date -Iseconds)'	'${nxf_main_ret:-0} >> '/data/microscape_v2/test_results_py/pipeline_info/pipeline_timing.tsv'
}

$NXF_ENTRY
