"""
microscape -- downstream analysis tools for amplicon sequencing data.

Designed to work with papa2's output, providing filtering, metadata loading,
renormalization, phylogenetic tree construction, ordination, co-occurrence
network analysis, and visualization export.
"""

try:                                  # generated by setuptools-scm at build time
    from ._version import version as __version__
except ImportError:                   # editable/source checkout without a build
    try:
        from importlib.metadata import version as _v
        __version__ = _v(__name__)
    except Exception:
        __version__ = "0.0.0+unknown"

from microscape.filter import filter_seqtab, plot_filter_summary
from microscape.metadata import load_metadata
from microscape.renormalize import renormalize
from microscape.phylogeny import build_phylogeny
from microscape.ordination import ordinate
from microscape.network import sparcc_network
from microscape.viz import export_viz

__all__ = [
    "filter_seqtab",
    "plot_filter_summary",
    "load_metadata",
    "renormalize",
    "build_phylogeny",
    "ordinate",
    "sparcc_network",
    "export_viz",
]
